### ISSUE TITLE
Cannot load user32.dll

### ISSUE THREAD

**Issue by kscieslinski** [bb107/MemoryModulePP#2]
Hi, I've successfully loaded ntdll.dll, kernel32.dll, advapi32.dll. However I've failed to load both user32.dll and ole32.dll (all x64).
I'd like to ask whether or not is known limitation.

My environment:
Windows x64 19042

**Comment by bb107** [comment]
When user32 is initialized, ntdll!RtlInitializeNtUserPfn is called to set the callback function pointer. This routine will check whether it has been set before setting the function pointer. Since user32.dll has been imported by default, repeated calls to initialization will fail and DllMain will return FALSE.
ole32 uses delayed import, but loading delayed import is currently not implemented.

**Comment by kscieslinski** [comment]
Great, thanks for explanation!
